#!/bin/bash
# =============================================================================
# Generate docker/.env with the host's UID/GID if it does not exist yet.
# - VS Code devcontainer:  runs automatically via initializeCommand
# - CLI (standalone):       run once with `bash docker/init-env.sh`
#
# Existing docker/.env is never overwritten — delete it to regenerate.
# =============================================================================
set -e

ENV_FILE="$(dirname "$0")/.env"

if [ -f "$ENV_FILE" ]; then
    echo "[init-env] $ENV_FILE already exists; leaving untouched"
    exit 0
fi

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

cat > "$ENV_FILE" <<EOF
# Auto-generated by docker/init-env.sh.
# Edit to override values; see docker/.env.example for all supported variables.
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
EOF

echo "[init-env] generated $ENV_FILE  (HOST_UID=${HOST_UID}, HOST_GID=${HOST_GID})"
