#!/bin/bash
# =============================================================================
# Generate .devcontainer/.env with the host's UID/GID + COMPOSE_PROJECT_NAME
# and pre-create Claude Code session-history dirs as the host user.
# - VS Code devcontainer:  runs automatically via initializeCommand
# - CLI (standalone):       run once with `bash .devcontainer/init-env.sh`
#
# Existing .devcontainer/.env is never overwritten — delete it to regenerate.
# =============================================================================
set -e

# >>> SINGLE SOURCE OF TRUTH for project / image / volume-path name. <<<
# When forking this template, edit this line, delete .devcontainer/.env, and re-run.
PROJECT_NAME="my-project"

# Pre-create Claude Code session-history dirs as the host user.
# Idempotent — runs every invocation, even when .env already exists, so that
# Docker never auto-creates these as root on first `compose up`.
mkdir -p "$HOME/.claude-stacks/$PROJECT_NAME"/{projects,sessions,todos,shell-snapshots}

ENV_FILE="$(dirname "$0")/.env"

if [ -f "$ENV_FILE" ]; then
    echo "[init-env] $ENV_FILE already exists; leaving untouched"
else
    HOST_UID="$(id -u)"
    HOST_GID="$(id -g)"

    if [ "$HOST_UID" = "0" ] || [ "$HOST_GID" = "0" ]; then
        echo "[init-env] ERROR: do not run as root (got UID=$HOST_UID, GID=$HOST_GID)." >&2
        echo "[init-env] Re-run as a regular user so the container user matches host file ownership." >&2
        if [ -n "${SUDO_USER:-}" ]; then
            echo "[init-env] hint: re-run without sudo (your real user is '$SUDO_USER')." >&2
        fi
        exit 1
    fi

    cat > "$ENV_FILE" <<EOF
# Auto-generated by .devcontainer/init-env.sh.
# Edit to override values; see .devcontainer/.env.example for all supported variables.
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
COMPOSE_PROJECT_NAME=${PROJECT_NAME}
EOF

    echo "[init-env] generated $ENV_FILE  (project=${PROJECT_NAME}, UID=${HOST_UID}, GID=${HOST_GID})"
fi
